# fly.toml file generated for mannele on 2022-07-15T22:08:35+02:00

app = "mannele"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
