# fly.toml file generated for mannele on 2022-07-15T22:08:35+02:00

app = "mannele"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build.args]
# We don't want to the build process to deploy the Discord commands
# Instead we do this with the release_command below
  DEPLOY_COMMANDS="NO"

[deploy]
  strategy = "rolling"
  release_command = "dist/deploy-commands.js"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
